### ISSUE TITLE
Better camera access UI flow

### ISSUE THREAD

**Issue by kober32** [wultra/swift-lime-auth#25]
When camera access is denied during `LimeAuthActivationUI` flow, there should be a way _(closure?)_ how to react to this (eg switch to manual code or canceling the activation).  Now, the UI is just sitting there without actual camera feed.

Also, when access is already denied, there should be UI to tell the user how to enable and the `entryCode` shortcut should be presented immediately. Currently is `LimeAuthActivationUI` presented and then immediately dismissed.

**Comment by petrdvorak** [comment]
@kober32 See how this is handled in the mobile token...

**Comment by hvge** [comment]
I think this issue is invalid. The `BeginActivationViewController` handles this situation properly and the only problem's when application chooses custom entry scene (e.g. selects `scanCode` as an initial view controller). In this case, it's application's responsibility to do not enter to scanner, when there's no access to the camera.
